# Generated by Django 4.1.6 on 2023-02-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم العهدة: ')),
                ('count', models.PositiveSmallIntegerField(verbose_name='العدد')),
            ],
        ),
        migrations.CreateModel(
            name='Reqeust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المستلم: ')),
                ('count', models.PositiveSmallIntegerField(verbose_name='العدد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='اختر العهدة: ')),
            ],
        ),
    ]
